"use client";
import {TongueRigPanel} from "./tongue-rig-panel";
import {useState} from 'react';
import {mouthContours,freshMouthRig} from './mouth-rig';
import type {useFaceRigController} from './face-rig-controller';
import type {FaceMotionChannel} from './face-rig';
import styles from './face-rig-panel.module.css';
const extraControls=[['mouthLowerDownLeft','왼쪽 아랫입술 내리기'],['mouthLowerDownRight','오른쪽 아랫입술 내리기'],['mouthPucker','입술 오므리기'],['mouthFunnel','오 모양'],['mouthPressLeft','왼쪽 입술 누르기'],['mouthPressRight','오른쪽 입술 누르기'],['mouthRollUpper','윗입술 말아 넣기'],['mouthRollLower','아랫입술 말아 넣기'],['mouthStretchLeft','왼쪽 가로 당기기'],['mouthStretchRight','오른쪽 가로 당기기']] as const;
const presets:{label:string;values:Partial<Record<FaceMotionChannel,number>>}[]=[{label:'아랫니만 드러내기',values:{mouthLowerDownLeft:.9,mouthLowerDownRight:.9}},{label:'오므리기',values:{mouthPucker:1}},{label:'오 모양',values:{mouthFunnel:.9}},{label:'입술 누르기',values:{jawOpen:.25,mouthPressLeft:1,mouthPressRight:1}},{label:'입술 말아 넣기',values:{jawOpen:.15,mouthRollUpper:1,mouthRollLower:1}},{label:'가로로 당기기',values:{mouthStretchLeft:1,mouthStretchRight:1}},{label:'윗니만 드러내기',values:{mouthUpperUpLeft:.9,mouthUpperUpRight:.9}},{label:'왼쪽 윗입술 올리기',values:{mouthUpperUpLeft:.9}},{label:'입 다물기',values:{}},{label:'작게 벌리기',values:{jawOpen:.3}},{label:'크게 벌리기',values:{jawOpen:1}},{label:'미소',values:{mouthSmileLeft:.8,mouthSmileRight:.8}},{label:'웃으며 벌리기',values:{jawOpen:.7,mouthSmileLeft:.8,mouthSmileRight:.8}},{label:'왼쪽 입꼬리',values:{mouthSmileLeft:.8}},{label:'입꼬리 내리기',values:{mouthFrownLeft:.8,mouthFrownRight:.8}}];
export function MouthRigPanel({face}:{face:ReturnType<typeof useFaceRigController>}){
 const [edge,setEdge]=useState<'upper'|'lower'>('upper'),[index,setIndex]=useState(4),c=mouthContours(face.profile.poses.neutral.points,face.telemetry.values,face.featureAlignment,face.mouthRig);
 return <details open aria-label="입모양 리그"><summary>입모양 리그 · 위·아래 각 9점</summary><p>입술 윤곽과 좌우 입꼬리를 따로 움직입니다. 입 다물기·미소·벌림을 아래 버튼으로 비교하세요.</p>
 <svg viewBox={`${c.cx-28} ${c.cy-10} 56 32`} style={{width:'100%',background:'#f1e2d1',borderRadius:8}} aria-label="입술 제어점 편집">{(['upper','lower'] as const).map(e=><g key={e}><polyline points={c[e].map(p=>p.join(',')).join(' ')} fill="none" stroke={e==='upper'?'#9a5777':'#a47742'} strokeWidth={.3}/>{c[e].map((p,i)=><circle key={i} role="button" tabIndex={0} aria-label={`${e==='upper'?'윗':'아랫'}입술 점 ${i+1}`} cx={p[0]} cy={p[1]} r={edge===e&&index===i?.7:.4} fill={edge===e&&index===i?'#d98427':'#795497'} onClick={()=>{setEdge(e);setIndex(i);}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setEdge(e);setIndex(i);}}}/>)}</g>)}</svg>
 <label>입술<select aria-label="편집할 입술" value={edge} onChange={e=>setEdge(e.target.value as typeof edge)}><option value="upper">윗입술</option><option value="lower">아랫입술</option></select></label>
 <label>제어점<select aria-label="입술 제어점 선택" value={index} onChange={e=>setIndex(Number(e.target.value))}>{Array.from({length:9},(_,i)=><option value={i} key={i}>{i+1}{i===0||i===8?' · 입꼬리 고정':''}</option>)}</select></label>
 <label>입술 곡선 · {face.mouthRig[edge][index].toFixed(2)}<input aria-label="입술 곡선 높이" disabled={index===0||index===8} type="range" min="-2" max="2" step=".1" value={face.mouthRig[edge][index]} onChange={e=>face.setMouthRig({...face.mouthRig,[edge]:face.mouthRig[edge].map((v,i)=>i===index?Number(e.target.value):v)})}/></label>
 <label>윗입술 올림 반응 · {(face.mouthRig.upperLipGain??1).toFixed(2)}<input aria-label="윗입술 올림 반응" type="range" min="0" max="3" step=".05" value={face.mouthRig.upperLipGain??1} onChange={e=>face.setMouthRig({...face.mouthRig,upperLipGain:Number(e.target.value)})}/></label>
 {(['mouthUpperUpLeft','mouthUpperUpRight'] as const).map((key,i)=><label key={key}>{i===0?'왼쪽':'오른쪽'} 윗입술 올림 · 원본 {Math.round((face.telemetry.raw[key]??0)*100)}% / 적용 {Math.round(face.telemetry.values[key]*100)}%<input aria-label={`${i===0?'왼쪽':'오른쪽'} 윗입술 수동 테스트`} type="range" min="0" max="1" step=".01" value={face.mode==='test'?face.manualValues[key]:face.telemetry.values[key]} onChange={e=>face.test(key,Number(e.target.value))}/></label>)}
 <details><summary>추가 입동작 · 원본과 적용값</summary>{extraControls.map(([key,label])=><label key={key}>{label} · 원본 {Math.round((face.telemetry.raw[key]??0)*100)}% / 적용 {Math.round(face.telemetry.values[key]*100)}%<input aria-label={`${label} 수동 테스트`} type="range" min="0" max="1" step=".01" value={face.mode==='test'?face.manualValues[key]:face.telemetry.values[key]} onChange={e=>face.test(key,Number(e.target.value))}/></label>)}</details>
 <TongueRigPanel face={face}/>
 {(['teeth','tongue'] as const).map(k=><label key={k}><span><input type="checkbox" aria-label={k==='teeth'?'치아 표시':'혀 표시'} checked={face.mouthRig[k]} onChange={e=>face.setMouthRig({...face.mouthRig,[k]:e.target.checked})}/>{k==='teeth'?'치아 표시':'혀 표시'}</span></label>)}
 <div className={styles.actions}>{presets.map(p=><button type="button" key={p.label} onClick={()=>{if(p.values.mouthUpperUpLeft||p.values.mouthUpperUpRight||p.values.mouthLowerDownLeft||p.values.mouthLowerDownRight)face.setMouthRig({...face.mouthRig,teeth:true});face.clearTest();face.setMode('test');for(const [k,v]of Object.entries(p.values))face.test(k as FaceMotionChannel,v);}}>{p.label}</button>)}<button type="button" onClick={()=>face.setMode('live')}>웹캠 입모양 연결</button><button type="button" onClick={()=>face.setMouthRig(freshMouthRig())}>입술 리그 초기화</button></div><p>입 너비·높이·벌림 비율은 본체 눈썹·입 맞추기에서 조절합니다. 얼굴 리그 저장으로 보관합니다. 웹캠의 좌우 윗입술 올림도 턱 벌림과 별도로 연결됩니다. 윗니는 고정된 위치에서 입술이 올라간 만큼 보이며, 반응이 약하면 무표정 보정 후 윗입술 올림 반응을 조절하세요.</p></details>;
}
