from __future__ import annotations

from typing import Any, Protocol

from .use_cases import (
    FontRegistrationCommand,
    FontUpdateCommand,
    ProviderSettingsCommand,
    SkillRegistrationCommand,
)


class AdministrationOperations(Protocol):
    def list_fonts(self, include_retired: bool) -> list[dict[str, Any]]: ...
    def search_google_fonts(self, query: str, korean_only: bool, offset: int, limit: int) -> dict[str, Any]: ...
    def import_google_font(self, family: str, variant: str) -> dict[str, Any]: ...
    def search_noonnu_fonts(self, query: str, page: int) -> dict[str, Any]: ...
    def get_noonnu_font(self, font_id: int) -> dict[str, Any]: ...
    def import_noonnu_font(self, font_id: int, variant: str) -> dict[str, Any]: ...
    def register_font(self, command: FontRegistrationCommand) -> dict[str, Any]: ...
    def update_font(self, command: FontUpdateCommand) -> dict[str, Any]: ...
    def list_provider_settings(self) -> list[dict[str, Any]]: ...
    def update_provider_settings(self, command: ProviderSettingsCommand) -> dict[str, Any]: ...
    def list_models(self) -> list[dict[str, Any]]: ...
    def list_skills(self, include_disabled: bool) -> list[dict[str, Any]]: ...
    def register_skill(self, command: SkillRegistrationCommand) -> dict[str, Any]: ...
    def list_skill_versions(self, skill_id: str) -> list[dict[str, Any]]: ...
    def activate_skill_version(self, skill_id: str, version_number: int) -> dict[str, Any]: ...
    def set_skill_enabled(self, skill_id: str, enabled: bool) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def workspace_summary(self) -> dict[str, Any]: ...

    def storage_operation(self, action: str, values: dict[str, Any]) -> dict[str, Any]: ...
