"""Build a local, searchable reference catalogue from a playlist checkpoint."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]/'output/japanese-playlist'
p=json.loads((root/'playlist.json').read_text());s=json.loads((root/'progress.json').read_text())
for shard in root.glob('progress-shard*.json'):
    other=json.loads(shard.read_text())
    for key,value in other.get('items',{}).items():
        if value.get('status')=='downloaded' or key not in s['items']:s['items'][key]=value
rows=[{**e,**s.get('items',{}).get(e['id'],{}),'index':i} for i,e in enumerate(p['entries'],1)]
for item in rows:
    if item['id']=='Gb-cE3hyu0c':item['analysis_id']='art_37efd433ddd74850af'
content='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>1분 일본어 · 레퍼런스 모음</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f6f2;color:#202622;font:16px system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:48px 24px}h1{font-size:32px;margin-bottom:10px}p{color:#5a625c;line-height:1.6}header{border-bottom:1px solid #d1d6ce;padding-bottom:24px}nav{display:flex;gap:12px;margin:24px 0;position:sticky;top:0;background:#f7f6f2;padding:12px 0;z-index:2}input,select{font:inherit;padding:12px;border:1px solid #bac2b7;border-radius:6px}input{flex:1}#grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:20px}article{background:#fff;border:1px solid #dfe3db;padding:16px;border-radius:8px}img{width:100%;height:160px;object-fit:contain;background:#eff1eb}h2{font-size:16px;line-height:1.6;margin:12px 0}small{color:#63715e}a{display:inline-block;margin:8px 12px 0 0;color:#285637}#count{font-weight:600;color:#285637}.failed{color:#9d4b35}.pending{color:#777}button{cursor:pointer}footer{margin-top:30px;font-size:13px;color:#697163}</style><main><header><small>HISOHISO / REFERENCE COLLECTION</small><h1>1분 일본어 · 레퍼런스 모음</h1><p>‘매일 1분 일본어’ 재생목록. 회차별 원본과 미리보기를 보관합니다.</p><div id="count"></div></header><nav><input id="search" placeholder="회차 번호 또는 제목 검색"><select id="status"><option value="all">전체</option><option value="downloaded">다운로드 완료</option><option value="failed">재시도 필요</option><option value="pending">대기 / 진행 중</option></select></nav><section id="grid"></section><footer>원본은 분석용 레퍼런스입니다. 긴 모음집도 원본 전체를 보관하며, 미리보기는 처음 60초입니다.</footer></main><script>
const rows=DATA; const grid=document.querySelector('#grid'),search=document.querySelector('#search'),filter=document.querySelector('#status');
document.querySelector('#count').textContent=`${rows.filter(x=>x.status==='downloaded').length} / ${rows.length}개 다운로드 완료`;
function draw(){grid.replaceChildren();rows.filter(x=>(filter.value==='all'||filter.value==='pending'?!['downloaded','failed'].includes(x.status)||filter.value==='all':x.status===filter.value)&&`${x.index} ${x.title}`.toLowerCase().includes(search.value.toLowerCase())).forEach(x=>{let article=document.createElement('article');let ids=x.artifact_ids||{};if(ids.Thumbnail){let img=document.createElement('img');img.loading='lazy';img.alt='';img.src=`http://localhost:8000/artifacts/${encodeURIComponent(ids.Thumbnail)}/content`;article.append(img)}let n=document.createElement('small');n.textContent=`${String(x.index).padStart(3,'0')} · ${Math.round((x.duration_ms||x.duration*1000||0)/1000)}초`;article.append(n);let title=document.createElement('h2');title.textContent=x.title||x.id;article.append(title);let state=document.createElement('div');state.className=x.status||'pending';state.textContent=x.status==='downloaded'?'보관 완료':x.status==='failed'?'재시도 필요':'대기 / 진행 중';article.append(state);function link(label,url){let a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noreferrer';article.append(a)}if(ids.ReferenceOriginal)link('원본 영상 열기',`http://localhost:8000/artifacts/${encodeURIComponent(ids.ReferenceOriginal)}/content`);if(ids.ProxyVideo)link('미리보기',`http://localhost:8000/artifacts/${encodeURIComponent(ids.ProxyVideo)}/content`);if(x.analysis_id)link('ChatGPT 분석',`http://localhost:3000/reference-results/${encodeURIComponent(x.analysis_id)}`);link('YouTube',`https://www.youtube.com/watch?v=${encodeURIComponent(x.id)}`);grid.append(article)})}
search.addEventListener('input',draw);filter.addEventListener('change',draw);draw();</script></html>'''
(root/'index.html').write_text(content.replace('DATA',json.dumps(rows,ensure_ascii=False).replace('<','\\u003c')))
print('catalogue updated',sum(x.get('status')=='downloaded' for x in rows),'/',len(rows))
